version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      labels:
        image-name: sinatra_app
    image: sinatra_app
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    environment:
      RACK_ENV: development
